name: CI/CD Pipeline
on:
  push:
    branches: [ main, CICD_Test ]
  pull_request:
    branches: [ main, CICD_Test ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Chạy các tests
    - name: Run Tests
      run: |
        docker-compose up -d
